version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - mqtt-network

  node-service:
    build: ./Sensor
    depends_on:
      - mosquitto
    networks:
      - mqtt-network

  python-service:
    build: ./Analytics
    depends_on:
      - mosquitto
    networks:
      - mqtt-network

  nestjs-service:
    build: ./event-info
    depends_on:
      - mosquitto
    ports:
      - 3000:3000
    networks:
      - mqtt-network

networks:
  mqtt-network:
    driver: bridge